table customer
	lineageTag: c505c265-8da0-4b7b-93cb-3beaa2ecca54

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 822caec9-74c7-481b-a909-4055135a3f4c
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 745d3932-19ff-4c06-b09d-41b820afef26
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	partition customer = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("E:\PORTFOLIO\DAX\sales-data.xlsx"), null, true),
				    customer_Sheet = Source{[Item="customer",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(customer_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

